// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 c0m4r

package main

import (
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
)

var completionOptionPattern = regexp.MustCompile(`(^|[[:space:]\[,(|/])(--?[[:alnum:]][[:alnum:]-]*)`)

func cmdCompletion(args []string) int {
	if len(args) != 1 || args[0] != "bash" {
		fatalf("completion", "usage: completion bash")
		return 2
	}
	if _, err := io.WriteString(os.Stdout, bashCompletionScript()); err != nil {
		fatalf("completion", "write error: %v", err)
		return 1
	}
	return 0
}

func completionOptions(helpText string) []string {
	options := map[string]bool{"--help": true}
	for _, match := range completionOptionPattern.FindAllStringSubmatchIndex(helpText, -1) {
		option := helpText[match[4]:match[5]]
		options[option] = true

		// Usage forms such as [-46n] and [-svL] describe compact short-option
		// groups. Offer the individual flags as well as the documented group.
		start, end := match[4], match[5]
		if start >= 2 && helpText[start-1] == '[' && end < len(helpText) && helpText[end] == ']' {
			group := option[1:]
			if len(group) > 1 && group != strings.ToUpper(group) {
				for _, character := range group {
					options["-"+string(character)] = true
				}
			}
		}
	}

	result := make([]string, 0, len(options))
	for option := range options {
		result = append(result, option)
	}
	sort.Strings(result)
	return result
}

func bashCompletionScript() string {
	names := make([]string, 0, len(appletHelp))
	for name := range appletHelp {
		names = append(names, name)
	}
	sort.Strings(names)

	var script strings.Builder
	script.WriteString(`# bash completion for ba6
# Generated by "ba6 completion bash". Source this file from Bash.
_ba6_complete()
{
	local cur applet="" word options=""
	local -i applet_index=0 i
	local applet_names=`)
	script.WriteString(bashSingleQuote(strings.Join(names, " ")))
	script.WriteString(`
	local global_options='--help -h --list --no-seccomp --seccomp=on --seccomp=off'

	cur=${COMP_WORDS[COMP_CWORD]}
	for ((i = 1; i < COMP_CWORD; i++)); do
		word=${COMP_WORDS[i]}
		case $word in
			--help|-h|--list|--no-seccomp|--seccomp=*) ;;
			-*) ;;
			*) applet=$word; applet_index=$i; break ;;
		esac
	done

	if [[ -z $applet ]]; then
		options=$applet_names
		if [[ $cur == -* ]]; then
			options=$global_options
		fi
		mapfile -t COMPREPLY < <(compgen -W "$options" -- "$cur")
		return
	fi

	if [[ ($applet == help || $applet == man) && COMP_CWORD -eq applet_index+1 ]]; then
		mapfile -t COMPREPLY < <(compgen -W "$applet_names" -- "$cur")
		return
	fi
	if [[ $applet == completion && COMP_CWORD -eq applet_index+1 ]]; then
		mapfile -t COMPREPLY < <(compgen -W 'bash' -- "$cur")
		return
	fi

	case $applet in
`)
	for _, name := range names {
		helpText, ok := appletHelp[name]
		if !ok {
			continue
		}
		fmt.Fprintf(&script, "\t\t%s) options=%s ;;\n", bashSingleQuote(name),
			bashSingleQuote(strings.Join(completionOptions(helpText), " ")))
	}
	script.WriteString(`		*) options='--help' ;;
	esac

	if [[ $cur == -* ]]; then
		mapfile -t COMPREPLY < <(compgen -W "$options" -- "$cur")
		return
	fi

	mapfile -t COMPREPLY < <(compgen -f -- "$cur")
	compopt -o filenames 2>/dev/null || true
}

complete -F _ba6_complete ba6
`)
	return script.String()
}

func bashSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
